added lint

diff --git a/.github/workflows/config.yaml b/.github/workflows/config.yaml
--- a/.github/workflows/config.yaml
+++ b/.github/workflows/config.yaml
@@ -11,10 +11,81 @@ env:
   COLLECTION_HANDLE: "sale"
   PRODUCT_HANDLE: "stread-pro-laufband"
 
-jobs: 
+jobs:
+  Prettier: 
+    runs-on: ubuntu-latest
+    steps: 
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with: 
+          node-version: 24
+
+      - name: Install Dependencies
+        run: npm ci
+
+      - name: Run Prettier Formatting
+        run: npx prettier "**/*.liquid" --write 
+
+  ES_lint: 
+    runs-on: ubuntu-latest
+    needs: Prettier
+    steps: 
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with: 
+          node-version: 24
+
+      - name: Install Dependencies
+        run: npm ci
+
+      - name: Run ES_lint
+        run: npm run lint      
+
+  Theme_Check: 
+    runs-on: ubuntu-latest
+    needs: ES_lint
+    steps: 
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Install Shopify CLI
+        run: npm install -g @shopify/cli @shopify/theme  
+
+      - name: Shopify theme Check
+        run: npm run theme:check
+
+  JSFileSize: 
+    needs: Theme_Check
+    runs-on: ubuntu-latest
+    steps: 
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Check JavaScript size
+        run: |
+          LIMIT=4000
+          LIMIT=500000
+
+          find assets -name "*.js" | while read file; do
+            SIZE=$(wc -c < "$file")
+
+            echo "$file : $SIZE"
+
+            if [ "$SIZE" -gt "$LIMIT" ]; then
+              echo "$file exceeds ${LIMIT} bytes"
+              exit 1
+            fi
+          done
 
   Shopify_theme_push:
     runs-on: ubuntu-latest
+    needs: JSFileSize
     outputs:
       current_theme_id: '${{ steps.create_theme.outputs.current_theme_id }}'
     steps:
@@ -52,7 +123,6 @@ jobs:
             echo "test_url: $current_theme_id"
             echo "current_theme_id=$current_theme_id" >> "$GITHUB_OUTPUT"
           fi
-
 
   lighthouse:
     runs-on: ubuntu-latest
@@ -94,7 +164,7 @@ jobs:
           }
           EOF
 
-          jq empty .lighthouserc.json && echo "✅ Valid JSON" || (echo "❌ Invalid JSON"; cat .lighthouserc.json; exit 1)
+          jq empty .lighthouserc.json && echo "Valid JSON" || (echo "Invalid JSON"; cat .lighthouserc.json; exit 1)
 
       - name: Run Lighthouse
         run: npx lhci autorun
