added file size

diff --git a/.github/workflows/config.yaml b/.github/workflows/config.yaml
--- a/.github/workflows/config.yaml
+++ b/.github/workflows/config.yaml
@@ -1,50 +1,142 @@
 name: Shopify Theme Pipeline
 
-on:
-  push:
+on: 
+  push: 
     branches-ignore:
       - main
+env: 
+  SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_STORE }}
+  SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_ADMIN_TOKEN }}
+  THEME_NAME: ${{ github.ref_name }}
 
-jobs:
-  Optimized:
+jobs: 
+  Prettier: 
     runs-on: ubuntu-latest
+    steps: 
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-    steps:
-      - uses: actions/checkout@v4
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with: 
+          node-version: 24
 
-      - name: Validate JavaScript size
-        run: |
-          FILE_LIMIT=$((200 * 1024))    # 200 KB
-          TOTAL_LIMIT=$((400 * 1024))   # 400 KB
+      - name: Install Dependencies
+        run: npm ci
 
-          TOTAL_SIZE=0
-          FAILED=0
+      - name: Run Prettier Formatting
+        run: npx prettier "**/*.liquid" --write 
 
-          while IFS= read -r file; do
-            SIZE=$(wc -c < "$file")
-            TOTAL_SIZE=$((TOTAL_SIZE + SIZE))
+  ES_lint: 
+    runs-on: ubuntu-latest
+    needs: Prettier
+    steps: 
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-            echo "$file : $SIZE bytes"
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with: 
+          node-version: 24
 
-            if [ "$SIZE" -gt "$FILE_LIMIT" ]; then
-              echo "❌ $file exceeds individual limit (200 KB)"
-              FAILED=1
-            fi
-          done < <(find assets -type f -name "*.js")
+      - name: Install Dependencies
+        run: npm ci
 
-          echo ""
-          echo "Total JavaScript Size: $TOTAL_SIZE bytes"
+      - name: Run ES_lint
+        run: npm run lint      
 
-          if [ "$TOTAL_SIZE" -gt "$TOTAL_LIMIT" ]; then
-            echo "❌ Total JavaScript size exceeds 400 KB"
+  Theme_Check: 
+    runs-on: ubuntu-latest
+    needs: ES_lint
+    steps: 
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Install Shopify CLI
+        run: npm install -g @shopify/cli @shopify/theme  
+
+      - name: Shopify theme Check
+        run: npm run theme:check
+
+  JSFileSize: 
+  needs: Theme_Check
+  runs-on: unbuntu-latest
+  steps: 
+    - name: Validate JavaScript size
+      run: |
+        FILE_LIMIT=$((200 * 1024))    # 200 KB
+        TOTAL_LIMIT=$((400 * 1024))   # 400 KB
+
+        TOTAL_SIZE=0
+        FAILED=0
+
+        while IFS= read -r file; do
+          SIZE=$(wc -c < "$file")
+          TOTAL_SIZE=$((TOTAL_SIZE + SIZE))
+
+          echo "$file : $SIZE bytes"
+
+          if [ "$SIZE" -gt "$FILE_LIMIT" ]; then
+            echo "❌ $file exceeds individual limit (200 KB)"
             FAILED=1
           fi
+        done < <(find assets -type f -name "*.js")
 
-          if [ "$FAILED" -eq 1 ]; then
-            echo ""
-            echo "🚫 JavaScript size validation failed."
-            exit 1
+        echo ""
+        echo "Total JavaScript Size: $TOTAL_SIZE bytes"
+
+        if [ "$TOTAL_SIZE" -gt "$TOTAL_LIMIT" ]; then
+          echo "❌ Total JavaScript size exceeds 400 KB"
+          FAILED=1
+        fi
+
+        if [ "$FAILED" -eq 1 ]; then
+          echo ""
+          echo "🚫 JavaScript size validation failed."
+          exit 1
+        fi
+
+        echo ""
+        echo "✅ JavaScript size validation passed."      
+
+  Shopify_theme_push: 
+    runs-on: ubuntu-latest
+    needs: JSFileSize
+    steps: 
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Install Shopify CLI
+        run: npm install -g @shopify/cli @shopify/theme 
+
+      - name: Find theme ID by name
+        id: find_theme
+        run: |
+          THEME_ID=$(shopify theme list --json \
+            | jq -r --arg NAME "$THEME_NAME" '.[] | select(.name==$NAME) | .id' \
+          )
+
+          if [ -z "$THEME_ID" ] || [ "$THEME_ID" = "null" ]; then
+            echo "Theme not found"
+            echo "theme_id=" >> "$GITHUB_OUTPUT"
+          else
+            echo "Theme found: $THEME_ID"
+            echo "theme_id=$THEME_ID" >> "$GITHUB_OUTPUT"
           fi
 
-          echo ""
-          echo "✅ JavaScript size validation passed."
+          echo "Found theme id: $THEME_ID"
+          echo "theme_id=$THEME_ID" >> "$GITHUB_OUTPUT"         
+
+      - name: Create Preview Theme
+ 
+        run: |
+          if [ "${{ steps.find_theme.outputs.theme_id }}" == "" ]; then
+            echo "New theme Creates"
+            shopify theme push --unpublished --theme "$THEME_NAME" || exit 1
+          else 
+            echo "Pushing to existing theme"
+            shopify theme push --theme ${{ steps.find_theme.outputs.theme_id }} --json || exit 1
+          fi  
+
+
+
