reverted

diff --git a/.github/workflows/config.yaml b/.github/workflows/config.yaml
--- a/.github/workflows/config.yaml
+++ b/.github/workflows/config.yaml
@@ -1,30 +1,101 @@
 name: Shopify Theme Pipeline
 
-on:
-  push:
+on: 
+  push: 
     branches-ignore:
       - main
+env: 
+  SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_STORE }}
+  SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_ADMIN_TOKEN }}
+  THEME_NAME: ${{ github.ref_name }}
 
-jobs:
-  Optimized:
+jobs: 
+  Prettier: 
     runs-on: ubuntu-latest
+    steps: 
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-    steps:
-      - uses: actions/checkout@v4
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with: 
+          node-version: 24
 
-      - name: Check JavaScript size
+      - name: Install Dependencies
+        run: npm ci
+
+      - name: Run Prettier Formatting
+        run: npx prettier "**/*.liquid" --write 
+
+  ES_lint: 
+    runs-on: ubuntu-latest
+    needs: Prettier
+    steps: 
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with: 
+          node-version: 24
+
+      - name: Install Dependencies
+        run: npm ci
+
+      - name: Run ES_lint
+        run: npm run lint      
+
+  Theme_Check: 
+    runs-on: ubuntu-latest
+    needs: ES_lint
+    steps: 
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Install Shopify CLI
+        run: npm install -g @shopify/cli @shopify/theme  
+
+      - name: Shopify theme Check
+        run: npm run theme:check
+
+  Shopify_theme_push: 
+    runs-on: ubuntu-latest
+    needs: Theme_Check
+    steps: 
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Install Shopify CLI
+        run: npm install -g @shopify/cli @shopify/theme 
+
+      - name: Find theme ID by name
+        id: find_theme
         run: |
-          LIMIT=500000
+          THEME_ID=$(shopify theme list --json \
+            | jq -r --arg NAME "$THEME_NAME" '.[] | select(.name==$NAME) | .id' \
+          )
 
-          find assets -name "*.js" | while read file; do
-            SIZE=$(wc -c < "$file")
+          if [ -z "$THEME_ID" ] || [ "$THEME_ID" = "null" ]; then
+            echo "Theme not found"
+            echo "theme_id=" >> "$GITHUB_OUTPUT"
+          else
+            echo "Theme found: $THEME_ID"
+            echo "theme_id=$THEME_ID" >> "$GITHUB_OUTPUT"
+          fi
 
-            echo "$file : $SIZE"
+          echo "Found theme id: $THEME_ID"
+          echo "theme_id=$THEME_ID" >> "$GITHUB_OUTPUT"         
 
-            if [ "$SIZE" -gt "$LIMIT" ]; then
-              echo "$file exceeds 500 KB"
-              exit 1
-            fi
-          done
+      - name: Create Preview Theme
+ 
+        run: |
+          if [ "${{ steps.find_theme.outputs.theme_id }}" == "" ]; then
+            echo "New theme Creates"
+            shopify theme push --unpublished --theme "$THEME_NAME" || exit 1
+          else 
+            echo "Pushing to existing theme"
+            shopify theme push --theme ${{ steps.find_theme.outputs.theme_id }} --json || exit 1
+          fi  
 
-          echo "Done"
+
+
